<h1><font color='blue'> 8E and 8F: Finding the Probability P(Y==1|X)</font></h1>

<h2><font color='Geen'> 8E: Implementing Decision Function of SVM RBF Kernel</font></h2>

<font face=' Comic Sans MS' size=3>After we train a kernel SVM model, we will be getting support vectors and their corresponsing coefficients $\alpha_{i}$

Check the documentation for better understanding of these attributes: 

https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html
<img src='https://i.imgur.com/K11msU4.png' width=500>

As a part of this assignment you will be implementing the ```decision_function()``` of kernel SVM, here decision_function() means based on the value return by ```decision_function()``` model will classify the data point either as positive or negative

Ex 1: In logistic regression After traning the models with the optimal weights $w$ we get, we will find the value $\frac{1}{1+\exp(-(wx+b))}$, if this value comes out to be < 0.5 we will mark it as negative class, else its positive class

Ex 2: In Linear SVM After traning the models with the optimal weights $w$ we get, we will find the value of $sign(wx+b)$, if this value comes out to be -ve we will mark it as negative class, else its positive class.

Similarly in Kernel SVM After traning the models with the coefficients $\alpha_{i}$ we get, we will find the value of 
$sign(\sum_{i=1}^{n}(y_{i}\alpha_{i}K(x_{i},x_{q})) + intercept)$, here $K(x_{i},x_{q})$ is the RBF kernel. If this value comes out to be -ve we will mark $x_{q}$ as negative class, else its positive class.

RBF kernel is defined as: $K(x_{i},x_{q})$ = $exp(-\gamma ||x_{i} - x_{q}||^2)$

For better understanding check this link: https://scikit-learn.org/stable/modules/svm.html#svm-mathematical-formulation
</font>

## Task E

> 1. Split the data into $X_{train}$(60), $X_{cv}$(20), $X_{test}$(20)

> 2. Train $SVC(gamma=0.001, C=100.)$ on the ($X_{train}$, $y_{train}$)

> 3. Get the decision boundry values $f_{cv}$ on the $X_{cv}$ data  i.e. ` `$f_{cv}$ ```= decision_function(```$X_{cv}$```)```  <font color='red'>you need to implement this decision_function()</font>

In [105]:
import numpy as np
import pandas as pd
from sklearn.datasets import make_classification
import numpy as np
from sklearn.svm import SVC
import math
from sklearn.model_selection import train_test_split
from tqdm import tqdm
import random

In [88]:
X, y = make_classification(n_samples=5000, n_features=5, n_redundant=2,
                           n_classes=2, weights=[0.7], class_sep=0.7, 
                           random_state=15)

train_X,test_X,train_y,test_y  = train_test_split(X,y,test_size=0.20,random_state=42)
train_X,train_CV,train_y,test_CV  = train_test_split(train_X,train_y,test_size=0.20,random_state=42)


In [89]:
s = pd.DataFrame(test_CV)

In [90]:
s[0].value_counts()

0    569
1    231
Name: 0, dtype: int64

### Pseudo code

clf = SVC(gamma=0.001, C=100.)<br>
clf.fit(Xtrain, ytrain)

<font color='green'>def</font> <font color='blue'>decision_function</font>(Xcv, ...): #use appropriate parameters <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color='green'>for</font> a data point $x_q$ <font color='green'>in</font> Xcv: <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color='grey'>#write code to implement $(\sum_{i=1}^{\text{all the support vectors}}(y_{i}\alpha_{i}K(x_{i},x_{q})) + intercept)$, here the values $y_i$, $\alpha_{i}$, and $intercept$ can be obtained from the trained model</font><br>
   <font color='green'>return</font> <font color='grey'><i># the decision_function output for all the data points in the Xcv</i></font>
    
fcv = decision_function(Xcv, ...)  <i># based on your requirement you can pass any other parameters </i>

<b>Note</b>: Make sure the values you get as fcv, should be equal to outputs of clf.decision_function(Xcv)


In [91]:


model = SVC(gamma=0.001, C=100.0, probability=True)
model.fit(train_X, train_y)

model_dec_value = model.decision_function(train_CV)

prams= model.get_params()
b =  model.intercept_
sv = model.support_vectors_
a = model.dual_coef_

custom_dec_val = []

def decision_function(x_cv, c, gamma):
    #print(x_cv)
    for cv in x_cv:
    #for i, cv in tqdm(enumerate(x_cv)):
        value = 0
        for j in range(len(sv)):
            l2_norm = np.linalg.norm(cv - sv[j])
            kernel = np.exp(-prams['gamma'] * (l2_norm**2))
            value += a[0][j] * kernel
        value = value + b
        custom_dec_val.append(value[0])
        
fcv = decision_function(train_CV, 100.0, 0.001)

In [92]:
print(prams)
print(b)
print(sv)
print(a)

{'C': 100.0, 'break_ties': False, 'cache_size': 200, 'class_weight': None, 'coef0': 0.0, 'decision_function_shape': 'ovr', 'degree': 3, 'gamma': 0.001, 'kernel': 'rbf', 'max_iter': -1, 'probability': True, 'random_state': None, 'shrinking': True, 'tol': 0.001, 'verbose': False}
[-1.80151873]
[[-0.45249961 -0.55624639 -0.18877168 -0.26346616  0.11359858]
 [ 0.71918122 -0.90416915 -0.18571414 -0.27647336 -0.18785388]
 [-0.97685553  0.1003584  -0.09967914 -0.12004848  0.39077859]
 ...
 [ 1.16313433 -0.29206536 -0.05199842 -0.07929317 -0.08525518]
 [ 0.21190377 -0.01954856 -0.01010565 -0.01360925  0.014668  ]
 [ 0.48453654  0.00724127  0.03051939  0.03859359 -0.08777591]]
[[-100.         -100.         -100.         -100.         -100.
  -100.         -100.         -100.         -100.         -100.
  -100.         -100.         -100.         -100.         -100.
  -100.         -100.         -100.         -100.         -100.
  -100.         -100.         -100.         -100.         -100.
  -

In [93]:
compare_decision_fun = pd.DataFrame(data= [model.decision_function(train_CV),custom_dec_val]).T
#sample results
compare_decision_fun.rename({0:'Cf_inbuilt',1:'manual_cf'},axis=1)[:5]

Cf_inbuilt  manual_cf
0    0.877196   0.877196
1   -1.120046  -1.120046
2   -3.563691  -3.563691
3   -0.631567  -0.631567
4   -1.192167  -1.192167

<strong>As we have binary target variables, Decision function concludes as when the data points gives postive points which in the postive side of hyperplane , simlarly negative means Hyperplane in negative direction </strong>

<h2><font color='Geen'> 8F: Implementing Platt Scaling to find P(Y==1|X)</font></h2>

Check this <a href='https://drive.google.com/open?id=133odBinMOIVb_rh_GQxxsyMRyW-Zts7a'>PDF</a>
<img src='https://i.imgur.com/CAMnVnh.png'>


## TASK F


> 4. Apply SGD algorithm with ($f_{cv}$, $y_{cv}$) and find the weight $W$ intercept $b$ ```Note: here our data is of one dimensional so we will have a one dimensional weight vector i.e W.shape (1,)``` 

> Note1: Don't forget to change the values of $y_{cv}$ as mentioned in the above image. you will calculate y+, y- based on data points in train data

> Note2: the Sklearn's SGD algorithm doesn't support the real valued outputs, you need to use the code that was done in the `'Logistic Regression with SGD and L2'` Assignment after modifying loss function, and use same parameters that used in that assignment.
<img src='https://i.imgur.com/zKYE9Oc.png'>
if Y[i] is 1, it will be replaced with y+ value else it will replaced with y- value

> 5. For a given data point from $X_{test}$, $P(Y=1|X) = \frac{1}{1+exp(-(W*f_{test}+ b))}$ where ` `$f_{test}$ ```= decision_function(```$X_{test}$```)```, W and b will be learned as metioned in the above step

__Note: in the above algorithm, the steps 2, 4 might need hyper parameter tuning, To reduce the complexity of the assignment we are excluding the hyerparameter tuning part, but intrested students can try that__


If any one wants to try other calibration algorithm istonic regression also please check these tutorials

1. http://fa.bianp.net/blog/tag/scikit-learn.html#fn:1

2. https://drive.google.com/open?id=1MzmA7QaP58RDzocB0RBmRiWfl7Co_VJ7

3. https://drive.google.com/open?id=133odBinMOIVb_rh_GQxxsyMRyW-Zts7a

4. https://stat.fandom.com/wiki/Isotonic_regression#Pool_Adjacent_Violators_Algorithm


In [94]:
#Calculate Y+ and y-
N_pos =0
N_neg = 0
for i in test_CV:
    if i ==1:
        N_pos+=1
    else:
        N_neg+=1


In [95]:
Y_pos = (N_pos+1)/(N_pos+2)
Y_neg  =1/(N_neg+2)

In [96]:
# Replace Postive test CV with Y_pos and 0 with Y_neg
Updated_testCV = []
for i in test_CV:
    if i ==1:
        Updated_testCV.append(Y_pos)
    else:
        Updated_testCV.append(Y_neg)


In [97]:

def initialize_weights():
    w = np.zeros(1)
    b = 0
    return w,b

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def logloss(y_true, y_pred):
    loss = 0
    for index in range(len(y_true)):
        a = (y_true[index] * math.log(y_pred[index], 10)) + \
        (1 - y_true[index]) * math.log(1 - y_pred[index], 10)
        b = (-1/len(y_true))
        loss = loss + a * b
    return loss

def gradient_dw(x, y, w, b):
    error = y - sigmoid(np.dot(x, w.T) + b)
    dw = x * error
    return dw

def gradient_db(x, y, w, b):
    db = y - sigmoid(np.dot(x, w.T) + b)
    return db

def probability(x, w, b):
    predicted = []
    probability = []
    for i in range(len(x)):
        z = np.dot(w, x[i]) + b
        sig = sigmoid(z)
        if sig >= 0.5:
            predicted.append(1)
        else:
            predicted.append(0)
        probability.append(sig)
    return np.array(predicted), np.array(probability)

def find_accuracy(actual, predicted):
    return round((np.sum((actual == predicted) / 
                                      len(actual))) * 100, 2)

def train(X_test, y_test, epochs, alpha, lr):
    
    
    global test_loss
    test_loss = []
    
    w, b = initialize_weights()
    for ep in range(epochs):
        print('Epoch:', ep + 1)
        for index in range(len(X_test)):
            r_index = random.randint(0, len(X_test) - 1)
            
            ln_eqn = np.dot(X_test[r_index], w.T) + b
            error = y_test[r_index] - sigmoid(ln_eqn)
            
            dw = X_test[r_index] * error
            db = error
            
            w = w + (alpha * dw)
            b = b + (alpha * db)
        
        
        predicted, score = probability(X_test, w, b)
        loss = logloss(y_test, score)
        test_loss.append(loss)
        te_acc = find_accuracy(y_test, predicted)
        print('Accuracy',te_acc)


    return w, b

In [98]:
lr  = 0.0001
alpha = 0.0001
N = len(Updated_testCV)
epochs = 10 

w, b = train(Updated_testCV, test_CV, epochs, alpha, lr)

Epoch: 1
Accuracy 71.12
Epoch: 2
Accuracy 71.12
Epoch: 3
Accuracy 71.12
Epoch: 4
Accuracy 71.12
Epoch: 5
Accuracy 71.12
Epoch: 6
Accuracy 71.12
Epoch: 7
Accuracy 71.12
Epoch: 8
Accuracy 71.12
Epoch: 9
Accuracy 71.12
Epoch: 10
Accuracy 71.12


In [99]:
w

array([0.11633561])

In [100]:
b

array([-0.15534377])

In [148]:
# Calibrate probablities
prob_values_calibrate = []
for (test_value) in custom_dec_val:
    #print(test_value)
    kernel = np.exp((-(w * (test_value+b))))
    prob = (1/(1+kernel))
    #print(prob)
    prob_values_calibrate.append((prob))



In [125]:
len(prob_values_calibrate)

800

In [152]:
df_prob_calibriate = pd.DataFrame(data={'Prob_score_1':prob_values_calibrate,'Actual_testCV':test_CV})

In [154]:
df_prob_calibriate['Prob_score_1'] = df_prob_calibriate['Prob_score_1'].str[0]

In [158]:
df_prob_calibriate.head(5)

Prob_score_1  Actual_testCV
0      0.520982              1
1      0.462975              0
2      0.393492              0
3      0.477130              0
4      0.460889              0

<strong>The empirical results show that after calibration gives best probablities which matches actual test_cv</strong>